name: PhotoTinder
targets:
  PhotoTinder:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: [Photo tinder]
    settings:
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGN_IDENTITY: ""
      AD_HOC_CODE_SIGNING_ALLOWED: YES
